In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import os
import json
from pandas import json_normalize
# pd.__version__

In [2]:
topic_file = '/Users/bew/Downloads/DataForThai_Pandas&SubTopic/SubTopic_dataforthai.csv'
topic_table = pd.read_csv(topic_file)


topic_table['รหัส'] = topic_table['รหัส'].astype(str)
# Function to add '0' to strings of length 4
def add_zero(s):
    if len(s) == 4:
        return '0' + s
    else:
        return s
# Applying the function to the DataFrame
topic_table['รหัส'] = topic_table['รหัส'].apply(lambda x: add_zero(x))


# topic_table.dtypes
topic_table = topic_table[:58] # 1461
# topic_table = topic_table[topic_table['รหัส']=='01450']
# print(topic_table)
# max(topic_table['จำนวนหน้า'])
topic_table

     รหัส                                       ประเภทธุรกิจ  จำนวน  จำนวนหน้า
0   01111                       การปลูกข้าวโพดที่ใช้เมล็ดแก่     24          1
1   01112               การปลูกธัญพืช (ยกเว้นข้าวและข้าวโพด)     34          1
2   01113                               การปลูกพืชตระกูลถั่ว     15          1
3   01114                                  การปลูกถั่วเหลือง      3          1
4   01115                การปลูกพืชน้ำมัน (ยกเว้นถั่วเหลือง)     10          1
5   01121                                    การปลูกข้าวจ้าว    640          2
6   01122                                  การปลูกข้าวเหนียว    374          1
7   01131  การปลูกพืชผักกินใบและพืชผักกินต้น รวมถึงการเพา...    134          1
8   01132  การปลูกพืชผักกินผลรวมถึงแตงชนิดต่าง ๆ รวมถึงกา...     48          1
9   01133                                การปลูกพืชผักกินหัว      9          1
10  01135                                 การปลูกมันสำปะหลัง     84          1
11  01136                                        การเพาะเห็ด     98          1
12  01139  การปลูกพืชผักอื่นๆ ซึ่งมิได้จัดประเภทไว้ในที่อื่น    307          1
13  01140                                        การปลูกอ้อย     74          1
14  01150                                       การปลูกยาสูบ      5          1
15  01161                                        การปลูกฝ้าย      1          1
16  01169  การปลูกพืชเส้นใยอื่นๆ ซึ่งมิได้จัดประเภทไว้ในท...      5          1
17  01191                          การปลูกข้าวโพดเลี้ยงสัตว์     30          1
18  01192  การปลูกพืชล้มลุกที่ใช้เป็นอาหารสัตว์ (ยกเว้นข้...     10          1
19  01193                                    การปลูกกล้วยไม้     28          1
20  01194                การปลูกไม้ดอกอื่นๆ (ยกเว้นกล้วยไม้)     23          1
21  01199  การปลูกพืชล้มลุกชนิดอื่นๆ ซึ่งมิได้จัดประเภทไว...     65          1
22  01210                                      การทำสวนองุ่น      7          1
23  01221                                     การปลูกสับปะรด     13          1
24  01222                                     การปลูกทุเรียน     42          1
25  01223                                        การปลูกลำไย      8          1
26  01224                                      การปลูกมะม่วง     14          1
27  01225                                       การปลูกกล้วย     19          1
28  01226                                      การปลูกมังคุด      5          1
29  01227                                        การปลูกเงาะ      1          1
30  01229  การปลูกไม้ผลเมืองร้อนและกึ่งร้อนอื่นๆซึ่งมิได้...     11          1
31  01231                                         การปลูกส้ม     16          1
32  01239  การปลูกไม้ผลตระกูลส้มอื่นๆซึ่งมิได้จัดประเภทไว...      9          1
33  01249  การปลูกไม้ผลเมืองหนาวอื่นๆ ซึ่งมิได้จัดประเภทไ...      2          1
34  01251                    การปลูกไม้ผลเปลือกแข็งที่กินได้      5          1
35  01259  การปลูกไม้ผลยืนต้นอื่นๆซึ่งมิได้จัดประเภทไว้ใน...     67          1
36  01261                                 การปลูกปาล์มน้ำมัน    175          1
37  01262                                     การปลูกมะพร้าว     43          1
38  01269  การปลูกไม้ยืนต้นอื่นๆที่ให้น้ำมันซึ่งมิได้จัดป...      6          1
39  01271                                         การทำไร่ชา     19          1
40  01272                                       การทำไร่กาแฟ     22          1
41  01279  การปลูกพืชอื่นๆที่นำไปทำเครื่องดื่มซึ่งมิได้จั...     35          1
42  01281                                        การปลูกพริก      8          1
43  01282                                     การปลูกพริกไทย      2          1
44  01289  การปลูกพืชอื่นๆประเภทเครื่องเทศเครื่องหอมยารัก...    592          2
45  01291                                  การปลูกต้นยางพารา    103          1
46  01292                        การปลูกพืชที่ใช้ในการถักสาน      8          1
47  01299  การปลูกพืชยืนต้นประเภทอื่นๆซึ่งมิได้จัดประเภทไ...    320          1
48  01301                                  การทำสวนไม้ประดับ     36          1
49  01302    การปลูกพืชการเพาะพันธุ์และการขยายพันธุ์พืชอื่นๆ    255          1
50  01411                            การเลี้ยงโคนมและโคเนื้อ    145          1
51  01412                    การเลี้ยงกระบือนมและกระบือเนื้อ      7          1
52  01419  การเลี้ยงโคและกระบือเพื่อวัตถุประสงค์อื่นๆซึ่ง...     19          1
53  01420    การเลี้ยงม้าลาล่อม้าล่อและสัตว์อื่นๆที่คล้ายม้า      7          1
54  01441                                       การเลี้ยงแกะ      4          1
55  01442                                       การเลี้ยงแพะ     24          1
56  01450                                      การเลี้ยงสุกร    808          3
57  01461                                    การเลี้ยงไก่ไข่    244          1

In [3]:
# topic_for_file = topic_table[topic_table['รหัส'] == no_topic]
# topic_for_file

In [4]:
# # Read JSON file
# file_path = f'/Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01111.json'  # Replace with your file path

# df = pd.read_json(file_path)

# # # Load JSON data into DataFrame
# # df = json_normalize(json_data)  # Use pd.DataFrame(json_data) if the JSON is already flat

# # df['สถานะ'] = df['สถานะ'].astype("string")
# df.dtypes
# # df

In [5]:
import pandas as pd
import os

# Initialize an empty DataFrame for the result
result = pd.DataFrame()

lastId = "01193"
value = ""

for index, row in topic_table.iterrows():
    
    value1 = row['รหัส']
    value2 = row['ประเภทธุรกิจ']
    
    if (int(value1) <= int(lastId)): continue
    
    # Construct the file path
    file_path = f'/Users/bew/Downloads/WebScrapperFor_DataForThai/Target/{value1}.json'
    
    # Check if the file exists
    if os.path.exists(file_path):
        try:
            # Read JSON file
            df = pd.read_json(file_path)
            
            # Add a new column with the business type
#             df['ประกอบธุรกิจ'] = value2
            
            # Concatenate the current DataFrame to the result DataFrame
            result = pd.concat([result, df], axis=0)
        
        except ValueError as e:
            print(f"Error reading JSON file at {file_path}: {e}")
    else:
        print(f"File not found: {file_path}")
    value = value1

print(f"lastId = {value1}")

File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01223.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01224.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01225.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01226.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01227.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01249.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01251.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01269.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01281.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01282.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01292.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01419.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01420.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01441.json
File not found: /Users/bew/Downloads/WebScrapperFor_DataForThai/Target/01442.json
lastId = 01461

In [6]:
# Reset the index of the final result DataFrame
result = result.reset_index(drop=True)

# result

In [7]:
result.columns.tolist()

result['เบอร์โทร'] = np.nan
# new_order = ['เลขทะเบียน', 'ชื่อบริษัทภาษาไทย', 'ชื่อบริษัทภาษาอังกฤษ', 'ประกอบธุรกิจ', 'หมวดธุรกิจ', 'สถานะ',
#              'วันที่จดทะเบียน', 'ทุนจดทะเบียน', 'ที่ตั้ง', 'ข้อมูลสำหรับการติดต่อ', 'เบอร์โทร', 'Website', 'ก่อตั้งโดย',
#              'หลักทรัพย์', 'ที่มา', 'สมัครงาน / ดูตำแหน่งงานว่าง', 'วันที่ร้าง', 'วันที่เลิก']
# result = result[new_order]
# result

In [8]:
# for index, row in topic_table.iterrows():
    
#     value1 = row['รหัส']
#     value2 = row['ประเภทธุรกิจ']
    
#     # Read JSON file
#     file_path = f'/Users/bew/Downloads/WebScrapperFor_DataForThai/Target/{value1}.json'  # Replace with your file path

#     df = pd.read_json(file_path)
    
#     df['ประกอบธุรกิจ'] = value2
    
#     result = pd.concat([result, df], axis=0)
    
    
# result

In [9]:
# result = result.drop(columns=['สมัครงาน / ดูตำแหน่งงานว่าง', 'วันที่ร้าง', 'หลักทรัพย์'])

result = result.applymap(str)
# result['เลขทะเบียน'] = result['เลขทะเบียน'].map(str)
# result['สถานะ'] = result['สถานะ'].astype("string")


# Step 1: Remove commas from the strings
result['ทุนจดทะเบียน'] = result['ทุนจดทะเบียน'].str.replace(',', '')
result['ทุนจดทะเบียน'] = result['ทุนจดทะเบียน'].str.replace(' บาท', '')
# Step 2: Convert the strings to numeric type (int or float)
result['ทุนจดทะเบียน'] = pd.to_numeric(result['ทุนจดทะเบียน'])

result.dtypes

เลขทะเบียน                     object
ประกอบธุรกิจ                   object
หมวดธุรกิจ                     object
สถานะ                          object
วันที่จดทะเบียน                object
ทุนจดทะเบียน                    int64
ก่อตั้งโดย                     object
ที่ตั้ง                        object
ชื่อบริษัทภาษาอังกฤษ           object
ชื่อบริษัทภาษาไทย              object
ข้อมูลสำหรับการติดต่อ          object
ที่มา                          object
ข้อมูลสำหรับติดต่อ             object
Website                        object
สมัครงาน / ดูตำแหน่งงานว่าง    object
วันที่ร้าง                     object
วันที่เลิก                     object
เบอร์โทร                       object
dtype: object

In [10]:
result = result[result['สถานะ']=='ยังดำเนินกิจการอยู่']
result = result[(result['ทุนจดทะเบียน'] >= 30000000)]

# def get_length(obj):
#     try:
#         return len(obj)
#     except TypeError:
#         return None

# for text in result['ทุนจดทะเบียน']:
#     print(text.apply(get_length))

# for index, row in result.iterrows():
    
#     value1 = row['เลขทะเบียน']
#     if value1.apply(len) != 13:
#         value1 = "0" + value1.astype(str)

result['เลขทะเบียน'] = "'0" + result['เลขทะเบียน'].astype(str)
# # Function to add '0' to strings of length 13
# def add_zero(s):
# #     s = str(s)  # Ensure the input is a string
#     if len(s) == 14:
#         return '0' + s
#     else:
#         return s

# # Applying the function to the DataFrame
# result['เลขทะเบียน'] = result['เลขทะเบียน'].apply(lambda x: add_zero(x))

# # Reset the index of the final result DataFrame
# result = result.reset_index(drop=True)

# result.dtypes

In [11]:
result['วันที่จดทะเบียน'] = result['วันที่จดทะเบียน'].str.replace(' มกราคม ','/1/')
result['วันที่จดทะเบียน'] = result['วันที่จดทะเบียน'].str.replace(' กุมภาพันธ์ ','/2/')
result['วันที่จดทะเบียน'] = result['วันที่จดทะเบียน'].str.replace(' มีนาคม ','/3/')
result['วันที่จดทะเบียน'] = result['วันที่จดทะเบียน'].str.replace(' เมษายน ','/4/')
result['วันที่จดทะเบียน'] = result['วันที่จดทะเบียน'].str.replace(' พฤษภาคม ','/5/')
result['วันที่จดทะเบียน'] = result['วันที่จดทะเบียน'].str.replace(' มิถุนายน ','/6/')
result['วันที่จดทะเบียน'] = result['วันที่จดทะเบียน'].str.replace(' กรกฎาคม ','/7/')
result['วันที่จดทะเบียน'] = result['วันที่จดทะเบียน'].str.replace(' สิงหาคม ','/8/')
result['วันที่จดทะเบียน'] = result['วันที่จดทะเบียน'].str.replace(' กันยายน ','/9/')
result['วันที่จดทะเบียน'] = result['วันที่จดทะเบียน'].str.replace(' ตุลาคม ','/10/')
result['วันที่จดทะเบียน'] = result['วันที่จดทะเบียน'].str.replace(' พฤศจิกายน ','/11/')
result['วันที่จดทะเบียน'] = result['วันที่จดทะเบียน'].str.replace(' ธันวาคม ','/12/')

In [12]:
result = result.reset_index(drop=True)
# result

In [13]:
# result.dtypes

In [14]:
file = '/Users/bew/Downloads/test.csv'
df = pd.read_csv(file)

df_updated = pd.concat([df, result], ignore_index=True)
df_updated = df_updated.drop_duplicates()
df_updated = df_updated.reset_index(drop=True)

df_updated.dtypes
df_updated

,เลขทะเบียน,ประกอบธุรกิจ,หมวดธุรกิจ,สถานะ,วันที่จดทะเบียน,ทุนจดทะเบียน,Website,ก่อตั้งโดย,ที่ตั้ง,ชื่อบริษัทภาษาอังกฤษ,ชื่อบริษัทภาษาไทย,ข้อมูลสำหรับการติดต่อ,ที่มา,สมัครงาน / ดูตำแหน่งงานว่าง,วันที่ร้าง,หลักทรัพย์,วันที่เลิก,เบอร์โทร,ข้อมูลสำหรับติดต่อ
0,'0105523007276,ผลิตเมล็ดพันธุ์ข้าวโพดและข้าวฟ่าง จำหน่ายเมล็ด...,การปลูกข้าวโพดที่ใช้เมล็ดแก่,ยังดำเนินกิจการอยู่,29/4/2523,245000000,NaN,"กรรมการ: นายกิตติพงษ์ ลิมปสุรัติ, นางจริยา วุฒ...",87 อาคารเอ็ม.ไทย ทาวเวอร์ ออลซีซันส์ เพลส ชั้น...,"PIONEER HI-BRED (THAILAND) CO., LTD.",บริษัท ไพโอเนีย ไฮ-เบรด (ไทยแลนด์) จำกัด,False,https://www.dataforthai.com/company/0105523007...,ดูตำแหน่งงานจาก JOBTOPGUN,NaN,NaN,NaN,'027922900,NaN
1,'0105539070673,จำหน่ายเมล็ดพันธุ์,การปลูกธัญพืช (ยกเว้นข้าวและข้าวโพด),ยังดำเนินกิจการอยู่,26/6/2539,162000000,NaN,"กรรมการ: นายโยชิฮิโร โอบาทาเกะ, นายเซน ทากามิย...",260 หมู่ที่ 13 ตำบลโนนท่อน อำเภอเมืองขอนแก่น จ...,"SAKATA SIAM SEED CO., LTD.",บริษัท ซาคาตะ สยาม ซีด จำกัด,False,https://www.dataforthai.com/company/0105539070...,NaN,NaN,NaN,NaN,'043001314,NaN
2,'0105563169226,เพาะปลูกผลิตผลทางการเกษตรกรรม,การปลูกข้าวจ้าว,ยังดำเนินกิจการอยู่,17/11/2563,100000000,NaN,กรรมการ: นางสาวอรวรรณ พัฒนพล,71 อาคารเอจีอาร์ ชั้นที่ 4 ถนนเจริญราษฎร์ แขวง...,SUBNAIDIN 666 COMPANY LIMITED,บริษัท ทรัพย์ในดิน 666 จำกัด,False,https://www.dataforthai.com/company/0105563169...,NaN,NaN,NaN,NaN,NaN,NaN
3,'0815524000023,ประกอบกิจการเกษตรกรรม,การปลูกธัญพืช (ยกเว้นข้าวและข้าวโพด),ยังดำเนินกิจการอยู่,17/9/2524,30000000,NaN,"กรรมการ: นายบุญส่ง ลีลามั่นคง, นางสุรัตน์ โพธิ...",141 หมู่ที่ 2 ถนนเพชรเกษม ตำบลอ่าวลึกเหนือ อำเ...,NaN,บริษัท ไพรสณฑ์ปาล์ม จำกัด,False,https://www.dataforthai.com/company/0815524000...,NaN,NaN,NaN,NaN,'075681136,NaN
4,'0105531018826,การเกษตรกรรมทุกชนิด และการให้บริการ,การปลูกธัญพืช (ยกเว้นข้าวและข้าวโพด),ยังดำเนินกิจการอยู่,16/3/2531,150000000,NaN,"กรรมการ: นางสาววรรณี จันทร์ไกรวัล, นางณัฐนี ตุ...",109 หมู่ที่ 9 ถนนสุวรรณศร ตำบลดงขี้เหล็ก อำเภอ...,"MORI FOOD PRODUCTS CO., LTD.",บริษัท สหปาล์ม ออยล์ จำกัด,False,https://www.dataforthai.com/company/0105531018...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,'0245531000101,ฟาร์มเลี้ยงไก่ไข่,การเลี้ยงไก่ไข่,ยังดำเนินกิจการอยู่,30/3/2531,50000000,nan,nan,124 หมู่ที่ 6 ตำบลย่านรี อำเภอกบินทร์บุรี จ.ปร...,SAENG URAI FARM COMPANY LIMITED,บริษัท แสงอุไรฟาร์ม จำกัด,False,https://www.dataforthai.com/company/0245531000...,nan,nan,NaN,nan,nan,nan
373,'0105559070334,การเลี้ยงสัตว์ประเภทอื่นๆ ซึ่งมิได้จัดประเภทไว...,การเลี้ยงไก่ไข่,ยังดำเนินกิจการอยู่,3/5/2559,30000000,nan,nan,168/2 หมู่ที่ 11 ตำบลบ้านพริก อำเภอบ้านนา จ.นค...,AKARA-ISE COMPANY LIMITED,บริษัท อัครา-ไอเซ จำกัด,False,https://www.dataforthai.com/company/0105559070...,nan,nan,NaN,nan,nan,สมาชิก dataforthai.com สามารถดูข้อมูลการติดต่อ...
374,'0505565005821,เลี้ยงไก่รุ่นพันธุ์ไข่ ผลิตไข่ไก่,การเลี้ยงไก่ไข่,ยังดำเนินกิจการอยู่,17/3/2565,220000000,nan,nan,161-161/1 หมู่ที่ 11 ตำบลหนองควาย อำเภอหางดง จ...,"R.P.M. HOLDING CO., LTD.",บริษัท อาร์.พี.เอ็ม. โฮลดิ้ง จำกัด,False,https://www.dataforthai.com/company/0505565005...,nan,nan,NaN,nan,nan,nan
375,'0245547000629,ฟาร์มไก่ไข่,การเลี้ยงไก่ไข่,ยังดำเนินกิจการอยู่,6/5/2547,200000000,nan,nan,37/8 หมู่ที่ 14 ตำบลศาลาแดง อำเภอบางน้ำเปรี้ยว...,S.L.P. ENTERPRISE COMPANY LIMITED,บริษัท เอส.แอล.พี. เอ็นเตอร์ไพรส์ จำกัด,False,https://www.dataforthai.com/company/0245547000...,nan,nan,NaN,nan,nan,nan
376,'0315559000954,การเลี้ยงไก่เนื้อ,การฆ่าและการบรรจุเนื้อสัตว์ปีกสด,ยังดำเนินกิจการอยู่,22/8/2559,51200000,nan,nan,186 หมู่ที่ 13 ตำบลตะคุ อำเภอปักธงชัย จ.นครราช...,"SPM FARM CO., LTD.",บริษัท เอสพีเอ็มฟาร์ม จำกัด,False,https://www.dataforthai.com/company/0315559000...,nan,nan,NaN,nan,nan,nan

In [15]:
# result[result['เลขทะเบียน'].str.len() != 13]

In [16]:
# result

In [17]:
file_name = 'test.csv'
file_path = '/Users/bew/Downloads/'

# Combine the file path and file name
full_path = os.path.join(file_path, file_name)

# result.to_csv(full_path, sep=',', index=False, header=True, encoding='utf-8') # รอบ 1
df_updated.to_csv(full_path, sep=',', index=False, header=True, encoding='utf-8') # รอบ 2+

print('finish')

finish

In [18]:
# # Step 1: Remove commas from the strings
# df['Capital'] = df['Capital'].str.replace(',', '')

# # Step 2: Convert the strings to numeric type (int or float)
# df['Capital'] = pd.to_numeric(df['Capital'])

# # Display the DataFrame to verify the changes
# df